{{ config
(
    materialized = 'table'
)
}}

SELECT 
TO_VARCHAR(DATE_TRUNC('day',BLOCK_TIMESTAMP), 'YYYY-MM-DD') AS date,
c.NAME,
COUNT(DISTINCT FROM_ADDRESS) AS active_wallets
FROM {{ source('arbitrum_raw', 'transactions') }} t
INNER JOIN ARBIGRANTS.DBT.ARBIGRANTS_LABELS_PROJECT_CONTRACTS c
ON c.CONTRACT_ADDRESS = t.TO_ADDRESS
-- AND BLOCK_TIMESTAMP < DATE_TRUNC('day',CURRENT_DATE())
AND BLOCK_TIMESTAMP >= CURRENT_DATE() - interval '13 months'
INNER JOIN ARBIGRANTS.DBT.ARBIGRANTS_LABELS_PROJECT_METADATA m
ON m.NAME = c.NAME
AND m.CHAIN IN ('Arbitrum One', 'Arbitrum Orbit')
GROUP BY 1,2