{{ config
(
    materialized = 'table'
)
}}

SELECT 
TO_VARCHAR(DATE_TRUNC('day',BLOCK_TIMESTAMP), 'YYYY-MM-DD') AS date,
COUNT(DISTINCT FROM_ADDRESS) AS active_wallets
FROM {{ source('arbitrum_raw', 'transactions') }} t
INNER JOIN ARBIGRANTS.DBT.ARBIGRANTS_LABELS_PROJECT_CONTRACTS c
ON c.CONTRACT_ADDRESS = t.TO_ADDRESS
AND BLOCK_TIMESTAMP < DATE_TRUNC('day',CURRENT_DATE())
AND BLOCK_TIMESTAMP >= CURRENT_DATE() - interval '13 months'
INNER JOIN ARBIGRANTS.DBT.ARBIGRANTS_LABELS_PROJECT_METADATA m
ON c.NAME = m.NAME
AND t.BLOCK_TIMESTAMP >= CASE
    WHEN TRY_TO_TIMESTAMP(m.GRANT_DATE, 'MM/DD/YYYY') IS NOT NULL THEN TRY_TO_TIMESTAMP(m.GRANT_DATE, 'MM/DD/YYYY')
    ELSE TO_TIMESTAMP('2023-03-01', 'YYYY-MM-DD')
END
AND m.CHAIN = 'Arbitrum One'
GROUP BY 1
