{{ config
(
    materialized = 'table'
)
}}

WITH cte AS (
  SELECT 
    NAME,
    TVL
  FROM ARBIGRANTS.DBT.ARBIGRANTS_ONE_DAY_TVL_BY_PROJECT
  WHERE DATE = TO_VARCHAR(DATE_TRUNC('day',CURRENT_DATE - INTERVAL '1 DAY'), 'YYYY-MM-DD')
),
total_tvl AS (
  SELECT SUM(TVL) AS TOTAL_TVL
  FROM cte
),
ranked_cte AS (
  SELECT 
    NAME,
    TVL,
    (SELECT TOTAL_TVL FROM total_tvl) AS TOTAL_TVL,
    ROUND(TVL / (SELECT TOTAL_TVL FROM total_tvl) * 100, 2) AS PCT_TVL,
    RANK() OVER (ORDER BY TVL DESC) AS rnk
  FROM cte
)
SELECT 
  CASE WHEN rnk <= 5 THEN NAME ELSE 'Other' END AS NAME,
  SUM(TVL) AS TVL,
  ROUND(SUM(TVL) / MAX(TOTAL_TVL) * 100, 2) AS PCT_TVL
FROM ranked_cte
GROUP BY CASE WHEN rnk <= 5 THEN NAME ELSE 'Other' END
ORDER BY TVL DESC