{{ config
(
    materialized = 'table'
)
}}

WITH cte AS (
  SELECT 
    m.NAME,
    SUM(h.TOTAL_LIQUIDITY_USD) AS TVL
  FROM ARBIGRANTS.DBT.ARBIGRANTS_LABELS_PROJECT_METADATA m
  INNER JOIN DEFILLAMA.TVL.HISTORICAL_TVL_PER_CHAIN h
  ON h.CHAIN = 'Arbitrum'
    AND LLAMA_NAME != ''
    AND h.PROTOCOL_NAME LIKE LLAMA_NAME || '%'
    AND DATE = CURRENT_DATE
GROUP BY 1
),
total_tvl AS (
  SELECT SUM(TVL) AS TOTAL_TVL
  FROM cte
),
ranked_cte AS (
  SELECT 
    NAME,
    TVL,
    (SELECT TOTAL_TVL FROM total_tvl) AS TOTAL_TVL,
    ROUND(TVL / (SELECT TOTAL_TVL FROM total_tvl) * 100, 2) AS PCT_TVL,
    RANK() OVER (ORDER BY TVL DESC) AS rnk
  FROM cte
)
SELECT 
  CASE WHEN rnk <= 5 THEN NAME ELSE 'Other' END AS NAME,
  SUM(TVL) AS TVL,
  ROUND(SUM(TVL) / MAX(TOTAL_TVL) * 100, 2) AS PCT_TVL
FROM ranked_cte
GROUP BY CASE WHEN rnk <= 5 THEN NAME ELSE 'Other' END
ORDER BY TVL DESC