{{ config
(
    materialized = 'table'
)
}}

WITH cte AS (
  SELECT 
    m.NAME,
    h.TOTAL_LIQUIDITY_USD AS TVL,
    SUM(h.TOTAL_LIQUIDITY_USD) OVER () AS TOTAL_TVL
  FROM ARBIGRANTS.DBT.ARBIGRANTS_LABELS_PROJECT_METADATA m
  INNER JOIN DEFILLAMA.TVL.HISTORICAL_TVL_PER_CHAIN h
  ON h.CHAIN = 'Arbitrum'
    AND h.PROTOCOL_NAME = LLAMA_NAME
    AND DATE = CURRENT_DATE
),
ranked_cte AS (
  SELECT 
    NAME,
    TVL,
    TOTAL_TVL,
    ROUND(TVL / TOTAL_TVL * 100, 2) AS PCT_TVL,
    RANK() OVER (ORDER BY TVL DESC) AS rnk
  FROM cte
)
SELECT 
  CASE WHEN rnk <= 5 THEN NAME ELSE 'Other' END AS NAME,
  SUM(TVL) AS TVL,
  ROUND(SUM(TVL) / MAX(TOTAL_TVL) * 100, 2) AS PCT_TVL
FROM ranked_cte
GROUP BY CASE WHEN rnk <= 5 THEN NAME ELSE 'Other' END
ORDER BY TVL DESC