{{ config
(
    materialized = 'table'
)
}}

WITH actives_24h AS (
SELECT COUNT(DISTINCT FROM_ADDRESS) as day_active_wallets
FROM ARBITRUM.RAW.TRANSACTIONS t
INNER JOIN ARBIGRANTS.DBT.ARBIGRANTS_LABELS_PROJECT_CONTRACTS c
ON c.CONTRACT_ADDRESS = t.TO_ADDRESS
AND BLOCK_TIMESTAMP < CURRENT_DATE
AND BLOCK_TIMESTAMP >= CURRENT_DATE - interval '1 day'
),

actives_growth_24h AS (
WITH active_wallet_counts AS (
  SELECT
      COUNT(DISTINCT CASE WHEN BLOCK_TIMESTAMP >= CURRENT_DATE - interval '1 day' AND BLOCK_TIMESTAMP < CURRENT_DATE THEN FROM_ADDRESS END) as past_day_wallets,
      COUNT(DISTINCT CASE WHEN BLOCK_TIMESTAMP < CURRENT_DATE - interval '1 day' AND BLOCK_TIMESTAMP >= CURRENT_DATE - interval '2 day' THEN FROM_ADDRESS END) as day_before_wallets
  FROM ARBITRUM.RAW.TRANSACTIONS t
  INNER JOIN ARBIGRANTS.DBT.ARBIGRANTS_LABELS_PROJECT_CONTRACTS c
  ON c.CONTRACT_ADDRESS = t.TO_ADDRESS
  AND BLOCK_TIMESTAMP >= CURRENT_DATE - interval '2 day'
)
SELECT
  ROUND((100 * (past_day_wallets / NULLIF(day_before_wallets, 0)) - 100), 1) AS day_growth
FROM active_wallet_counts
),

actives_7d AS (
SELECT COUNT(DISTINCT FROM_ADDRESS) as week_active_wallets
FROM ARBITRUM.RAW.TRANSACTIONS t
INNER JOIN ARBIGRANTS.DBT.ARBIGRANTS_LABELS_PROJECT_CONTRACTS c
ON c.CONTRACT_ADDRESS = t.TO_ADDRESS
AND BLOCK_TIMESTAMP < CURRENT_DATE
AND BLOCK_TIMESTAMP >= CURRENT_DATE - interval '7 day'
),

actives_growth_7d AS (
WITH active_wallet_counts AS (
  SELECT
      COUNT(DISTINCT CASE WHEN BLOCK_TIMESTAMP >= CURRENT_DATE - interval '7 day' AND BLOCK_TIMESTAMP < CURRENT_DATE THEN FROM_ADDRESS END) as past_day_wallets,
      COUNT(DISTINCT CASE WHEN BLOCK_TIMESTAMP < CURRENT_DATE - interval '7 day' AND BLOCK_TIMESTAMP >= CURRENT_DATE - interval '14 day' THEN FROM_ADDRESS END) as day_before_wallets
  FROM ARBITRUM.RAW.TRANSACTIONS t
  INNER JOIN ARBIGRANTS.DBT.ARBIGRANTS_LABELS_PROJECT_CONTRACTS c
  ON c.CONTRACT_ADDRESS = t.TO_ADDRESS
  AND BLOCK_TIMESTAMP >= CURRENT_DATE - interval '14 day'
)
SELECT
  ROUND((100 * (past_day_wallets / NULLIF(day_before_wallets, 0)) - 100), 1) AS week_growth
FROM active_wallet_counts
),

actives_1m AS (
SELECT COUNT(DISTINCT FROM_ADDRESS) as month_active_wallets 
FROM ARBITRUM.RAW.TRANSACTIONS t
INNER JOIN ARBIGRANTS.DBT.ARBIGRANTS_LABELS_PROJECT_CONTRACTS c
ON c.CONTRACT_ADDRESS = t.TO_ADDRESS
AND BLOCK_TIMESTAMP < CURRENT_DATE
AND BLOCK_TIMESTAMP >= CURRENT_DATE - interval '1 month'
),

actives_growth_1m AS (
WITH active_wallet_counts AS (
  SELECT
      COUNT(DISTINCT CASE WHEN BLOCK_TIMESTAMP >= CURRENT_DATE - interval '1 month' AND BLOCK_TIMESTAMP < CURRENT_DATE THEN FROM_ADDRESS END) as past_day_wallets,
      COUNT(DISTINCT CASE WHEN BLOCK_TIMESTAMP < CURRENT_DATE - interval '1 month' AND BLOCK_TIMESTAMP >= CURRENT_DATE - interval '2 month' THEN FROM_ADDRESS END) as day_before_wallets
  FROM ARBITRUM.RAW.TRANSACTIONS t
  INNER JOIN ARBIGRANTS.DBT.ARBIGRANTS_LABELS_PROJECT_CONTRACTS c
  ON c.CONTRACT_ADDRESS = t.TO_ADDRESS
  AND BLOCK_TIMESTAMP >= CURRENT_DATE - interval '2 month'
)
SELECT
  ROUND((100 * (past_day_wallets / NULLIF(day_before_wallets, 0)) - 100), 1) AS month_growth
FROM active_wallet_counts
)

SELECT * FROM actives_24h, actives_growth_24h, actives_7d, actives_growth_7d, actives_1m, actives_growth_1m