{{ config
(
    materialized = 'table'
)
}}

with grantees AS (
SELECT 
TO_VARCHAR(DATE_TRUNC('day',DATE), 'YYYY-MM-DD') AS date,
SUM(h.TOTAL_LIQUIDITY_USD) AS TVL
FROM ARBIGRANTS.DBT.ARBIGRANTS_LABELS_PROJECT_METADATA m
INNER JOIN DEFILLAMA.TVL.HISTORICAL_TVL_PER_CHAIN h
ON h.CHAIN = 'Arbitrum'
AND LLAMA_NAME != ''
AND h.PROTOCOL_NAME LIKE LLAMA_NAME || '%'
AND DATE < DATE_TRUNC('day',CURRENT_DATE())
AND h.DATE >= CASE
    WHEN TRY_TO_TIMESTAMP(m.GRANT_DATE, 'MM/DD/YYYY') IS NOT NULL THEN TRY_TO_TIMESTAMP(m.GRANT_DATE, 'MM/DD/YYYY')
    ELSE TO_TIMESTAMP('2023-03-01', 'YYYY-MM-DD')
END
AND DATE >= CURRENT_DATE() - interval '13 months'
AND m.CHAIN = 'Arbitrum One'
GROUP BY 1
)

, prices AS (
SELECT 
DATE_TRUNC('day',HOUR) AS date,
LAST_VALUE(USD_PRICE) OVER (PARTITION BY DATE_TRUNC('day', HOUR) ORDER BY HOUR) AS USD_PRICE
FROM COMMON.PRICES.TOKEN_PRICES_HOURLY_EASY
WHERE SYMBOL = 'ETH'
AND ETHEREUM_ADDRESS = '0x0000000000000000000000000000000000000000'
AND HOUR >= CURRENT_DATE() - interval '13 months'
QUALIFY ROW_NUMBER() OVER (PARTITION BY DATE_TRUNC('day', HOUR) ORDER BY HOUR DESC) = 1
)

SELECT 
m.DATE,
m.TVL,
m.TVL/p.USD_PRICE AS TVL_ETH
FROM grantees m
LEFT JOIN prices p
ON m.DATE = p.DATE