{{ config
(
    materialized = 'table'
)
}}

SELECT
COUNT(NAME) AS NUM_GRANTEES,
SUM(TOTAL_MILESTONES) AS TOTAL_MILESTONES,
SUM(MILESTONES_COMPLETED) AS MILESTONES_COMPLETED,
SUM(MILESTONES_COMPLETED) / SUM(TOTAL_MILESTONES) AS PCT_MILESTONES_COMPLETED,
AVG(CASE WHEN MILESTONES_COMPLETED = TOTAL_MILESTONES THEN 1 ELSE 0 END) AS PCT_FULL_COMPLETION,
AVG(CASE WHEN MILESTONES_COMPLETED >= 1 THEN 1 ELSE 0 END) AS PCT_NON_ZERO_PROGRESS
FROM ARBIGRANTS.DBT.ARBIGRANTS_LABELS_PROJECT_MILESTONES
