{{ config
(
    materialized = 'table'
)
}}

WITH total AS (
SELECT 
TO_VARCHAR(DATE_TRUNC('month',DATE), 'YYYY-MM-DD') AS date,
LAST_VALUE(TVL) OVER (PARTITION BY DATE_TRUNC('month', DATE) ORDER BY DATE) AS TVL 
FROM ARBIGRANTS.DBT.ARBIGRANTS_ONE_TOTAL_TVL
WHERE DATE < DATE_TRUNC('day',CURRENT_DATE())
AND DATE >= CURRENT_DATE() - interval '13 months'
QUALIFY ROW_NUMBER() OVER (PARTITION BY DATE_TRUNC('month', DATE) ORDER BY DATE DESC) = 1)

, prices AS (
SELECT 
DATE_TRUNC('month',HOUR) AS date,
LAST_VALUE(USD_PRICE) OVER (PARTITION BY DATE_TRUNC('month', HOUR) ORDER BY HOUR) AS USD_PRICE
FROM COMMON.PRICES.TOKEN_PRICES_HOURLY_EASY
WHERE SYMBOL = 'ETH'
AND ETHEREUM_ADDRESS = '0x0000000000000000000000000000000000000000'
AND HOUR >= CURRENT_DATE() - interval '13 months'
QUALIFY ROW_NUMBER() OVER (PARTITION BY DATE_TRUNC('month', HOUR) ORDER BY HOUR DESC) = 1
)

SELECT 
m.DATE,
m.TVL,
m.TVL/p.USD_PRICE AS TVL_ETH
FROM total m
LEFT JOIN prices p
ON m.DATE = p.DATE