{{ config
(
    materialized = 'table'
)
}}

SELECT 
TO_VARCHAR(DATE_TRUNC('month',DATE), 'YYYY-MM-DD') AS date,
LAST_VALUE(TVL) OVER (PARTITION BY DATE_TRUNC('month', DATE) ORDER BY DATE) AS TVL 
FROM ARBIGRANTS.DBT.ARBIGRANTS_ONE_TOTAL_TVL
WHERE DATE < DATE_TRUNC('day',CURRENT_DATE())
AND DATE >= CURRENT_DATE() - interval '13 months'
QUALIFY ROW_NUMBER() OVER (PARTITION BY DATE_TRUNC('month', DATE) ORDER BY DATE DESC) = 1