{{ config
(
    materialized = 'table'
)
}}

with grantees AS (
SELECT 
TO_VARCHAR(DATE_TRUNC('week',DATE), 'YYYY-MM-DD') AS date,
LAST_VALUE(TVL) OVER (PARTITION BY DATE_TRUNC('week', DATE) ORDER BY DATE) AS TVL
FROM (
    SELECT 
    DATE,
    SUM(TVL) AS TVL
    FROM
    (
        SELECT
        DATE,
        m.GRANT_DATE,
        h.TOTAL_LIQUIDITY_USD AS TVL,
        ROW_NUMBER() OVER (PARTITION BY h.PROTOCOL_NAME, DATE ORDER BY h.NEAREST_DATE DESC) AS rn
        FROM ARBIGRANTS.DBT.ARBIGRANTS_LABELS_PROJECT_METADATA m
        INNER JOIN DEFILLAMA.TVL.HISTORICAL_TVL_PER_CHAIN h
        ON h.CHAIN = 'Arbitrum Nova'
        AND LLAMA_NAME != ''
        AND h.PROTOCOL_NAME LIKE LLAMA_NAME || '%'
        AND DATE < DATE_TRUNC('day',CURRENT_DATE())
        AND DATE >= CURRENT_DATE() - interval '13 months'
        AND m.CHAIN = 'Arbitrum Nova'
    )
    WHERE DATE >= CASE
        WHEN TRY_TO_TIMESTAMP(GRANT_DATE, 'MM/DD/YYYY') IS NOT NULL THEN TRY_TO_TIMESTAMP(GRANT_DATE, 'MM/DD/YYYY')
        ELSE TO_TIMESTAMP('2023-03-01', 'YYYY-MM-DD')
    END
    AND rn = 1
    GROUP BY 1
)
QUALIFY ROW_NUMBER() OVER (PARTITION BY DATE_TRUNC('week', DATE) ORDER BY DATE DESC) = 1
)

, prices AS (
SELECT 
DATE_TRUNC('week',HOUR) AS date,
LAST_VALUE(USD_PRICE) OVER (PARTITION BY DATE_TRUNC('week', HOUR) ORDER BY HOUR) AS USD_PRICE
FROM COMMON.PRICES.TOKEN_PRICES_HOURLY_EASY
WHERE SYMBOL = 'ETH'
AND ETHEREUM_ADDRESS = '0x0000000000000000000000000000000000000000'
AND HOUR >= CURRENT_DATE() - interval '13 months'
QUALIFY ROW_NUMBER() OVER (PARTITION BY DATE_TRUNC('week', HOUR) ORDER BY HOUR DESC) = 1
)

SELECT 
m.DATE,
m.TVL,
m.TVL/p.USD_PRICE AS TVL_ETH
FROM grantees m
LEFT JOIN prices p
ON m.DATE = p.DATE